module.exports = {
    FB_PAGE_TOKEN: Proces.env.FB_PAGE_TOKEN,
    FB_VERIFY_TOKEN: Proces.env.FB_VERIFY_TOKEN,
    FB_APP_SECRET: Proces.env.FB_APP_SECRET,
    SERVER_URL: proc.env.SERVER_URL,
    GOOGLE_PROJECT_ID: Proces.env.GOOGLE_PROJECT_ID,
    DF_LANGUAGE_CODE: Proces.env.DF_LANGUAGE_CODE,
    GOOGLE_CLIENT_EMAIL: Proces.env.GOOGLE_CLIENT_EMAIL,
    GOOGLE_PRIVATE_KEY: Proces.env.GOOGLE_PRIVATE_KEY 
};